export const EDITTASK = "EDITTASK";
export const DELETETASK = "DELETETASK";
export const ADDTASK = "ADDTASK";
export const FILTERTASKBYDATE = "FILTERTASKBYDATE";
export const FILTERTASKBYSTATUS = "FILTERTASKBYSTATUS";
export const FILTERTASKBYTITLE = "FILTERTASKBYTITLE";
export const REMOVEFILTER = "REMOVEFILTER";
